-- ============================================================
-- CODE REVIEW ASSISTANT
-- Schema do banco de dados
-- PostgreSQL / Supabase
-- ============================================================


-- ============================================================
-- TABELA: pull_requests
-- ============================================================

create table if not exists public.pull_requests (
    id bigint generated by default as identity primary key,

    repo_full_name text not null,

    pr_number integer not null,

    title text,

    author text,

    action text,

    state text,

    head_sha text,

    url text,

    criado_em timestamptz not null default now(),

    atualizado_em timestamptz not null default now(),

    constraint pull_requests_repo_pr_unique
        unique (repo_full_name, pr_number)
);


-- ============================================================
-- TABELA: analises
-- ============================================================

create table if not exists public.analises (
    id bigint generated by default as identity primary key,

    pr_id bigint not null,

    head_sha text not null,

    resumo text,

    problemas jsonb,

    nota_geral integer,

    status text not null default 'pendente',

    criado_em timestamptz not null default now(),

    github_comment_id bigint,

    github_comment_url text,

    comentario_status text not null default 'pendente',

    comentario_erro text,

    erro text,

    constraint analises_pull_request_fk
        foreign key (pr_id)
        references public.pull_requests(id)
        on delete cascade,

    constraint analises_pr_sha_unique
        unique (pr_id, head_sha)
);